[package]
name = "zk_storage_proof"
authors = [""]
type = "bin"
compiler_version = "0.10.4"

[dependencies]
noir_trie_proofs = { git = "https://github.com/aragonzkresearch/noir-trie-proofs", tag = "main", directory = "lib" }